name: "Deploy CodigoFacilito"

on:
  push:
    branches: ["main"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    step:
      run: echo "Hacemos pull del codigo"
      run: echo "Correr migraciones"
      run: echo "Generar Binario"
      run: echo "Publicar version"